apiVersion: v1
kind: ConfigMap
metadata:
  name: ciao
  namespace: <namespace_name>
data:
  # SECRET_KEY_BASE: "sensitive_secret_key_base"
  # SMTP_ADDRESS: smtp.yourhost.com
  # SMTP_EMAIL_FROM: "ciao@yourhost.com"
  # SMTP_EMAIL_TO: "you@yourhost.com"
  # SMTP_PORT: 587
  # SMTP_AUTHENTICATION: plain
  # SMTP_DOMAIN: smtp.yourhost.com
  # SMTP_ENABLE_STARTTLS_AUTO: true
  # SMTP_USERNAME: ciao
  # SMTP_PASSWORD: "sensitive_password"
  TIME_ZONE: "Vienna"