apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: backup
  namespace: <namespace_name>
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: busybox
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Performing backup
          restartPolicy: OnFailure