apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ciao-pvc
  namespace: <namespace_name>
  labels:
    app.kubernetes.io/name: ciao
    app.kubernetes.io/version: "1.6.12"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
  storageClassName: "hcloud-volumes"