apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-db
  namespace: <namespace_name>
spec:
  serviceName: postgresql-db-service
  selector:
    matchLabels:
      app: postgresql-db
  replicas: 2
  template:
    metadata:
      labels:
        app: postgresql-db
    spec:
      # affinity:
      #   podAntiAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #     - labelSelector:
      #         matchExpressions:
      #           - key: "app"
      #             operator: In
      #             values:
      #             - postgres-db
      #       topologyKey: "kubernetes.io/hostname"
      containers:
        - name: postgresql-db
          image: postgres:latest
          volumeMounts:
            - name: postgresql-db-disk
              mountPath: /data
          env:
            - name: POSTGRES_PASSWORD
              value: testpassword
            - name: PGDATA
              value: /data/pgdata
          ports:
            - name: psql
              containerPort: 5432
              protocol: TCP
  volumeClaimTemplates:
    - metadata:
        name: postgresql-db-disk
      spec:
        storageClassName: "hcloud-volumes"
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 50Mi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-db-lb
  namespace: <namespace_name>
spec:
  selector:
    app: postgresql-db
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432